import { SpecificationWithProject, ViewerContent } from '../types';
import { renderMarkdown } from '../utils/markdown';
import '../styles/spec-viewer.css';

interface SpecViewerProps {
  content: ViewerContent;
  onRegenerate?: (spec: SpecificationWithProject) => void;
  isRegenerating?: boolean;
}

export default function SpecViewer({ content, onRegenerate, isRegenerating }: SpecViewerProps) {
  switch (content.kind) {
    case 'idle':
      return <EmptyState />;
    case 'loading':
      return <LoadingState message={content.message ?? 'Loading…'} />;
    case 'error':
      return <ErrorState message={content.message} />;
    case 'generated':
      return (
        <Article
          title={content.spec.projectName}
          subtitle={content.spec.projectDescription}
          markdown={content.spec.content}
          stamp="UNSAVED · PREVIEW"
        />
      );
    case 'saved': {
      const projectName = content.spec.project?.name ?? 'Untitled';
      const filename = `${slugify(projectName)}-v${content.spec.version}.md`;
      return (
        <Article
          title={projectName}
          subtitle={content.spec.project?.description ?? undefined}
          markdown={content.spec.content}
          version={content.spec.version}
          createdAt={content.spec.created_at}
          stamp={`SPEC-KIT v${content.spec.version} · SAVED`}
          onDownload={() => downloadMarkdown(filename, content.spec.content)}
          onRegenerate={onRegenerate ? () => onRegenerate(content.spec) : undefined}
          isRegenerating={isRegenerating}
        />
      );
    }
    default:
      return null;
  }
}

interface ArticleProps {
  title: string;
  subtitle?: string | null;
  markdown: string;
  version?: number;
  createdAt?: string;
  stamp?: string;
  onDownload?: () => void;
  onRegenerate?: () => void;
  isRegenerating?: boolean;
}

function Article({
  title,
  subtitle,
  markdown,
  version,
  createdAt,
  stamp,
  onDownload,
  onRegenerate,
  isRegenerating,
}: ArticleProps) {
  const html = renderMarkdown(markdown);
  return (
    <article className="spec-article">
      <header className="spec-article-header">
        {stamp && <div className="spec-stamp">{stamp}</div>}
        <h2 className="spec-title">{title}</h2>
        {subtitle && <p className="spec-subtitle">{subtitle}</p>}
        <div className="spec-meta">
          {version !== undefined && <span className="badge">v{version}</span>}
          {createdAt && (
            <time className="muted" dateTime={createdAt}>
              {new Date(createdAt).toLocaleString()}
            </time>
          )}
          <span className="spec-meta-spacer" />
          {onDownload && (
            <button type="button" className="ghost-button" onClick={onDownload} title="Download as Markdown">
              <span aria-hidden="true">↓</span> .md
            </button>
          )}
          {onRegenerate && (
            <button
              type="button"
              className="ghost-button primary"
              onClick={onRegenerate}
              disabled={isRegenerating}
              title="Generate a new version"
            >
              <span aria-hidden="true">{isRegenerating ? '◌' : '↻'}</span>{' '}
              {isRegenerating ? 'Regenerating…' : 'Regenerate'}
            </button>
          )}
        </div>
      </header>
      <div
        className="spec-body"
        // Markdown is generated by Gemini, then escaped in renderMarkdown()
        // before any structural markup is added.
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </article>
  );
}

function EmptyState() {
  return (
    <div className="empty-state">
      <div className="empty-state-rule" aria-hidden="true" />
      <div className="empty-state-icon" aria-hidden="true">
        ✎
      </div>
      <h2>No spec selected</h2>
      <p>
        Enter a project idea above and click <strong>Generate Specification</strong>.
      </p>
      <p className="muted">
        Generated specs follow the{' '}
        <a href="https://github.com/github/spec-kit" target="_blank" rel="noreferrer">
          github/spec-kit
        </a>{' '}
        template and are saved to Supabase.
      </p>
    </div>
  );
}

function LoadingState({ message }: { message: string }) {
  return (
    <div className="loading-state">
      <div className="spinner" aria-hidden="true" />
      <p>{message}</p>
    </div>
  );
}

function ErrorState({ message }: { message: string }) {
  return (
    <div className="error-state">
      <h2>Something went wrong</h2>
      <p>{message}</p>
      <p className="muted">Check the backend logs and try again.</p>
    </div>
  );
}

// ---- helpers ----
function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'spec';
}
